### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by JohnPeel** [Villavu/Simba#405]
Tests Suite for testing most of Simba.

**Comment by MerlijnWajer** [comment]
Most of Simba -> let's aim for some parts to be tested. Most is a stretch.

**Comment by JohnPeel** [comment]
Should actually be testing our exported stuff, though we could also have test suite of MML methods and maybe some of the features.

**Comment by R030t1** [comment]
Is there anything like JUnit for FPC/Lazarus? @JohnPeel did you intend to test the GUI or only the interface to Lape?

**Comment by nielsAD** [comment]
[fpcunit](http://wiki.lazarus.freepascal.org/fpcunit) and [FPTest](http://wiki.freepascal.org/FPTest are the most common testing frameworks, I think.

We could also go for a more integration approach and use scripts for testing.

**Comment by ghost** [comment]
We need Ada 8.1.0 as default. It's much easier than either Scar, PascalScript and la-pe.

I use it to create AGI. It's bug-free.
The reason I am not an administrator at the forum (I know you tried to, Merljin, even the silent administrator) is because of the "The God" title. Just give that to me after changing my forum username to Ōnō.

I'll create the bug-free runescape bot in a while, even with their extreme Anti-Bot recomendation system. Vorkath is the calibration. The scorpion is literary i, the imaginary number. In the JaGeX source code, they allow a fire-blast when the scorpion is 3 tiles away, then vorkath is easier, since the drake stops spitting the scorpion egg for that player account after that. Even if you leave and whatever. Just doesn't anymore. Test it with your III Age account.

**Comment by MerlijnWajer** [comment]
@Zyt3x - I legitimately don't understand what you were saying here. :-D

**Comment by ghost** [comment]
Oh, then don't worry about it. :-)

**Comment by ollydev** [comment]
In simba1500 scripts can now be placed in `tests/` which github actions will run.
